[project]
name = "budjetame"
version = "0.1.0"
description = "Web app for personal budjeting"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "pydantic-settings>=2.10.1",
    "pydantic>=2.11.7",
    "sqlmodel>=0.0.24",
]
