"""empty message

Revision ID: 9f6805ee51f5
Revises: 4ad19c98faef
Create Date: 2025-09-05 22:45:45.184994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9f6805ee51f5'
down_revision: Union[str, Sequence[str], None] = '4ad19c98faef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movement', sa.Column('type', sa.String(), server_default='loss', nullable=False))
    op.alter_column('movement', 'type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movement', 'type')
    # ### end Alembic commands ###
